### ISSUE TITLE
vtkimagedata as input/output parameters example

### ISSUE THREAD

**Issue by lambacini** [Kitware/vtkWasmBenchmarks#2]
Can we give vtkImageData generated by vtk.js as a parameter. I want to create polydata from the image created by vtk.js and show the image again on vtk.js after smoothing operations. I would appreciate it if you could share an example that we can take as an vtkImageData input-output parameter.

**Comment by jspanchu** [comment]
If I understand correctly, do you want to pass the vtkImageData javascript object into VTK C++ and then back out?

No, vtk.js cannot interop like that with VTK C++ as of right now. But stay tuned, as this interop is on our radar.
